name: Rust

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test_all --verbose
      env:
        RUST_MIN_STACK: 9999999
